// Generates db/seed.sql from db/seed-data.ts.
// Run with: npm run db:generate-seed
import fs from 'fs';
import path from 'path';
import { questions, type QuestionSeed } from './seed-data';

const esc = (s: string) => s.replace(/'/g, "''");

/** Validate authored content and render the deterministic deployment artifact. */
export function renderSeedSql(seedQuestions: readonly QuestionSeed[] = questions): string {
  const expectedLevels = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'] as const;
  if (
    seedQuestions.length !== 36 ||
    expectedLevels.some((level) => seedQuestions.filter((question) => question.cefrLevel === level).length !== 6)
  ) {
    throw new Error('expected exactly 6 questions for each CEFR level');
  }
  const naturalKeys = new Set<string>();
  for (const question of seedQuestions) {
    if (
      !question.promptWord.trim() ||
      question.promptWord.length > 100 ||
      !question.questionText.trim() ||
      question.questionText.length > 1_000
    ) {
      throw new Error(`invalid English content for "${question.promptWord}" (${question.cefrLevel})`);
    }
    const naturalKey = `${question.cefrLevel}\u0000${question.promptWord}`;
    if (naturalKeys.has(naturalKey)) {
      throw new Error(`duplicate question key "${question.promptWord}" (${question.cefrLevel})`);
    }
    naturalKeys.add(naturalKey);
    for (const lang of ['te', 'hi', 'es', 'zh'] as const) {
      const translation = question.translations[lang];
      if (
        !translation ||
        !translation.word.trim() ||
        translation.word.length > 500 ||
        !translation.question.trim() ||
        translation.question.length > 4_000 ||
        translation.examples.length !== 3
      ) {
        throw new Error(`incomplete ${lang} translation for "${question.promptWord}" (${question.cefrLevel})`);
      }
      for (const example of translation.examples) {
        if (
          !example.en.trim() ||
          example.en.length > 4_000 ||
          !example.native.trim() ||
          example.native.length > 4_000
        ) {
          throw new Error(`empty example in ${lang} for "${question.promptWord}"`);
        }
      }
    }
  }

  const lines = [
    '-- Seed data for ai_english. GENERATED by db/generate-seed.ts -- do not edit by hand.',
    `-- ${seedQuestions.length} questions (6 per CEFR level), translations for te/hi/es/zh.`,
    '-- Idempotent: updates content in place by (cefr_level, prompt_word); never deletes user data.',
    'BEGIN;',
  ];
  for (const question of seedQuestions) {
    const translations = esc(JSON.stringify(question.translations));
    lines.push(
      `INSERT INTO questions (cefr_level, prompt_word, question_text, translations) VALUES ('${question.cefrLevel}', '${esc(question.promptWord)}', '${esc(question.questionText)}', '${translations}'::jsonb) ON CONFLICT (cefr_level, prompt_word) DO UPDATE SET question_text = EXCLUDED.question_text, translations = EXCLUDED.translations;`,
    );
  }
  lines.push('COMMIT;', '');
  return lines.join('\n');
}

export function writeSeedSql(
  outputPath = defaultSeedSqlPath(),
  seedQuestions: readonly QuestionSeed[] = questions,
  log: (message: string) => void = console.log,
): void {
  fs.writeFileSync(outputPath, renderSeedSql(seedQuestions), 'utf8');
  log(`wrote db/seed.sql with ${seedQuestions.length} questions`);
}

export function defaultSeedSqlPath(moduleDirectory = __dirname): string {
  return path.join(moduleDirectory, 'seed.sql');
}

// Stryker disable all: direct-execution behavior is subprocess-tested; a
// mutated CommonJS identity check otherwise executes this CLI while Vitest is
// importing the library and produces a mutation-runner bootstrap error.
if (require.main === module) writeSeedSql();
// Stryker restore all
