// Generates db/seed.sql from db/seed-data.ts.
// Run with: npm run db:generate-seed
import fs from 'fs';
import path from 'path';
import { questions } from './seed-data';

const esc = (s: string) => s.replace(/'/g, "''");

const levels = new Set(questions.map((q) => q.cefrLevel));
if (levels.size !== 6) throw new Error('expected questions for all 6 CEFR levels');
const naturalKeys = new Set<string>();
for (const q of questions) {
  const naturalKey = `${q.cefrLevel}\u0000${q.promptWord}`;
  if (naturalKeys.has(naturalKey)) {
    throw new Error(`duplicate question key "${q.promptWord}" (${q.cefrLevel})`);
  }
  naturalKeys.add(naturalKey);
  for (const lang of ['te', 'hi', 'es', 'zh'] as const) {
    const t = q.translations[lang];
    if (!t || !t.word || !t.question || t.examples.length !== 3) {
      throw new Error(`incomplete ${lang} translation for "${q.promptWord}" (${q.cefrLevel})`);
    }
    for (const ex of t.examples) {
      if (!ex.en || !ex.native) throw new Error(`empty example in ${lang} for "${q.promptWord}"`);
    }
  }
}

const lines: string[] = [];
lines.push('-- Seed data for ai_english. GENERATED by db/generate-seed.ts -- do not edit by hand.');
lines.push(`-- ${questions.length} questions (6 per CEFR level), translations for te/hi/es/zh.`);
lines.push('-- Idempotent: updates content in place by (cefr_level, prompt_word); never deletes user data.');
lines.push('BEGIN;');
for (const q of questions) {
  const json = esc(JSON.stringify(q.translations));
  lines.push(
    `INSERT INTO questions (cefr_level, prompt_word, question_text, translations) VALUES ('${q.cefrLevel}', '${esc(q.promptWord)}', '${esc(q.questionText)}', '${json}'::jsonb) ON CONFLICT (cefr_level, prompt_word) DO UPDATE SET question_text = EXCLUDED.question_text, translations = EXCLUDED.translations;`,
  );
}
lines.push('COMMIT;');
lines.push('');

fs.writeFileSync(path.join(__dirname, 'seed.sql'), lines.join('\n'), 'utf8');
console.log(`wrote db/seed.sql with ${questions.length} questions`);
